# Chonost Project - Yarn Configuration v2.1.0
# ====================================

# Network settings
network-timeout: 300000
network-concurrency: 8

# Registry settings
npmRegistryServer: "https://registry.npmjs.org/"

# Package resolution
nodeLinker: node-modules
enableGlobalCache: true
compressionLevel: mixed

# Workspace settings
workspaces:
  - "packages/*"
  - "services/*"

# Package installation
enableScripts: true
enableInlineBuilds: true
enableInlineHunks: true

# Security settings
enableStrictSsl: true
enableNetwork: true

# Cache settings
cacheFolder: "./.yarn/cache"

# Logging
logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard

# Package extensions
packageExtensions:
  "@excalidraw/excalidraw@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"

# Plug'n'Play settings
pnpMode: loose
pnpFallbackMode: all
