apiVersion: v1
kind: Service
metadata:
  name: rag-service
  namespace: default
  labels:
    app: rag-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: rag-service