name: AI Code Review via MANUS API

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  ai-review:
    if: |
      contains(github.event.comment.body, '@manus') &&
      github.event.comment.user.login == 'billzzz10' &&
      (github.event.issue.pull_request != null || github.event.pull_request != null)

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read
      issues: write

    steps:
      - name: Get PR Number
        id: pr-info
        run: |
          if [ "${{ github.event.issue.pull_request }}" != "" ]; then
            echo "pr_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          else
            echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          fi

      - name: Get PR Details and Diff
        id: pr-details
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ steps.pr-info.outputs.pr_number }};

            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            const maxFiles = 20;
            const maxPatchSize = 10000;

            let diffContent = '';
            diffContent += `Pull Request #${prNumber}: ${pr.title}\n\n`;
            diffContent += `Description: ${pr.body || 'No description provided'}\n\n`;
            diffContent += `Branch: ${pr.head.ref} → ${pr.base.ref}\n`;
            diffContent += `Files changed: ${files.length}\n`;
            diffContent += `Additions: +${pr.additions} | Deletions: -${pr.deletions}\n\n`;
            diffContent += '---\n\n';

            const limitedFiles = files.slice(0, maxFiles);

            for (const file of limitedFiles) {
              diffContent += `File: ${file.filename}\n`;
              diffContent += `Status: ${file.status} | Changes: +${file.additions} -${file.deletions}\n\n`;

              if (file.patch) {
                const patch = file.patch.length > maxPatchSize 
                  ? file.patch.substring(0, maxPatchSize) + '\n... (ตัดเนื้อหาเกินขนาด)'
                  : file.patch;
                diffContent += `${patch}\n\n`;
              } else {
                diffContent += '(ไฟล์ไบนารีหรือมีขนาดใหญ่เกินไป)\n\n';
              }
              diffContent += '---\n\n';
            }

            if (files.length > maxFiles) {
              diffContent += `หมายเหตุ: แสดงเฉพาะ ${maxFiles} จากทั้งหมด ${files.length} ไฟล์\n`;
            }

            const fs = require('fs');
            fs.writeFileSync('pr_diff.txt', diffContent);

            core.setOutput('pr_title', pr.title);
            core.setOutput('files_count', files.length);

      - name: แจ้งเริ่มรีวิว
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.pr-info.outputs.pr_number }},
              body: '🤖 **เริ่มต้นการรีวิวโค้ดด้วย MANUS API...**\n\n⏳ กำลังวิเคราะห์ไฟล์จำนวน ${{ steps.pr-details.outputs.files_count }} ไฟล์'
            });

      - name: เรียก MANUS API
        id: ai-review
        env:
          MANUS_API_KEY: ${{ secrets.MANUS_API_KEY }}
        run: |
          DIFF_CONTENT=$(cat pr_diff.txt)

          USER_PROMPT="กรุณารีวิว pull request นี้และตอบกลับเป็นภาษาไทย โดยมีหัวข้อดังนี้:

          1. **สรุปโดยรวม**: อธิบายว่าโค้ดนี้แก้ไขอะไร
          2. **คุณภาพโค้ด**: โครงสร้าง ความอ่านง่าย ความดูแลรักษา
          3. **ปัญหาที่อาจเกิดขึ้น**: bug, logic ผิด, edge case
          4. **ความปลอดภัย**: ช่องโหว่หรือความเสี่ยง
          5. **ประสิทธิภาพ**: จุดที่ควรปรับปรุงให้เร็วขึ้น
          6. **แนวทางที่ดี**: มาตรฐานการเขียนโค้ด
          7. **ข้อเสนอแนะเฉพาะจุด**: บรรทัดไหนควรแก้หรือปรับ

          กรุณาตอบกลับเป็นภาษาไทยทั้งหมด และใช้ markdown พร้อม emoji เพื่อให้อ่านง่าย

          นี่คือรายละเอียดของโค้ดที่เปลี่ยนแปลง:

          $DIFF_CONTENT"

          JSON_PAYLOAD=$(jq -n \
            --arg key "$MANUS_API_KEY" \
            --arg input "$USER_PROMPT" \
            '{api_key: $key, input: $input}')

          RESPONSE=$(curl -s -X POST \
            https://api.manus.ai/review \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD")

          echo "API Response received"

          REVIEW_CONTENT=$(echo "$RESPONSE" | jq -r '.content // empty')

          if [ -z "$REVIEW_CONTENT" ]; then
            echo "Error: No content in response"
            ERROR_MSG=$(echo "$RESPONSE" | jq -r '.error.message // "Unknown error"')
            echo "Error message: $ERROR_MSG"

            echo "review_result=❌ **เกิดข้อผิดพลาด**: ไม่สามารถรับผลรีวิวจาก AI ได้\n\nข้อผิดพลาด: $ERROR_MSG" >> $GITHUB_OUTPUT
            exit 1
          fi

          echo "review_result<<EOF" >> $GITHUB_OUTPUT
          echo "$REVIEW_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "✅ การรีวิวเสร็จสมบูรณ์"

      - name: โพสต์ผลรีวิว
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const reviewResult = `${{ steps.ai-review.outputs.review_result }}`;

            let body = '## 🤖 ผลการรีวิวโค้ดโดย AI\n\n';

            if (reviewResult && reviewResult.trim() !== '' && !reviewResult.includes('เกิดข้อผิดพลาด')) {
              body += reviewResult;
              body += '\n\n---\n';
              body += '**โมเดลที่ใช้:** MANUS API\n';
              body += '**แพลตฟอร์ม:** External API\n';
              body += '\n💡 *พิมพ์ `@manus` เพื่อขอรีวิวใหม่อีกครั้ง*';
            } else if (reviewResult && reviewResult.includes('เกิดข้อผิดพลาด')) {
              body += reviewResult;
              body += '\n\n---\n';
              body += '**แนวทางแก้ไข:**\n';
              body += '- ตรวจสอบว่า API Key ถูกต้องและยังไม่หมดโควต้า\n';
              body += '- ตรวจสอบว่าเซิร์ฟเวอร์ MANUS ยังออนไลน์\n';
              body += '- ลองพิมพ์ `@manus` อีกครั้ง';
            } else {
              body += '⚠️ **เกิดข้อผิดพลาดไม่ทราบสาเหตุ**\n\n';
              body += 'ไม่สามารถรีวิวโค้ดได้ กรุณาตรวจสอบ log หรือลองใหม่อีกครั้ง';
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.pr-info.outputs.pr_number }},
              body: body
            });
